### ISSUE TITLE
[Suggestion] Add a building guide

### ISSUE THREAD

**Issue by TheBlueBurger** [VukkyLtd/SaladBind#2]
Would be good with a part of the README, or a separate file to tell you how to build this

**Comment by Vukkyy** [comment]
A compilation guide for compiling the software?

Run `npm i`, then `npm run compile`. We might add that later, thanks for your suggestion!

**Comment by vtheskeleton** [comment]
Hello! There are pre-compiled binaries available, if you wish to compile it yourself you can do so by installing node, running `npm i` where you cloned the repository to install dependencies and then running `npm run compile`

**Comment by vtheskeleton** [comment]
Also something to add, I will be adding a guide to compile it

**Comment by vtheskeleton** [comment]
This has now been implemented, thank you for your suggestion.
