### ISSUE TITLE
Autoupdate from github

### ISSUE THREAD

**Issue by WalkxCode** [VukkyLtd/SaladBind#24]
Would be useful if it auto-updates from github!

**Comment by TheBlueBurger** [comment]
Already a suggestion in discord, there's a thread about it to, but it can be moved to here I guess

**Comment by TheBlueBurger** [comment]
It should be optional if this is a thing

**Comment by WalkxCode** [comment]
> 
> 
> It should be optional if this is a thing

Settings menu 👁️👁️

**Comment by memedmusic** [comment]
This would be a helpful feature. Im might try code something to do this over the next few days

**Comment by vtheskeleton** [comment]
There is a pr for this which will be merged soon

**Comment by Vukkyy** [comment]
skeller that's not how this works!

**Comment by vtheskeleton** [comment]
i forgot that feature exists
