### ISSUE TITLE
Ethermine doesn't work on T-Rex Miner

### ISSUE THREAD

**Issue by technoranter** [VukkyLtd/SaladBind#30]
Trying to run ethermine with T-rex miner leads to earnings not showing up on Salad.

**Comment by vtheskeleton** [comment]
this happens outside bind too.

**Comment by WalkxCode** [comment]
Trex works differently for passing the worker on different pools. For nicehash it would be -u `wallet.rigid`. But for Ethermine it's -u `wallet` -w `rig.id` :)

**Comment by WalkxCode** [comment]
Vukky reacted with rocket emoji

**Comment by WalkxCode** [comment]
_Remove the invalid tag?_

**Comment by vtheskeleton** [comment]
> Trex works differently for passing the worker on different pools. For nicehash it would be -u `wallet.rigid`. But for Ethermine it's -u `wallet` -w `rig.id` :)

this is the conclusion i came to this morning

**Comment by vtheskeleton** [comment]
Angaros' guide has it incorrect too

**Comment by vtheskeleton** [comment]
A patch has been made and it will be included in the next update.

I have personally tested it and can see my worker pop up on salads ethermine.
