### ISSUE TITLE
Salad token always incorrect

### ISSUE THREAD

**Issue by thepwrtank18** [VukkyLtd/SaladBind#4]
I put in the correct token, but it always says it's false

![image](https://user-images.githubusercontent.com/57580668/127536675-253acf3a-750f-49e7-8f0e-ff3c02bcf988.png)

**Comment by Vukkyy** [comment]
What's the character length of your token?

**Comment by thepwrtank18** [comment]
603 chars

**Comment by Vukkyy** [comment]
Are you sure this is your entire token? Try pressing F12 and going to the Application tab.
![image](https://user-images.githubusercontent.com/46850780/127560923-930fdb5b-c78e-4977-b228-4a9f99d68962.png)
Then, uncollapse Cookies and click on app.salad.io.
![image](https://user-images.githubusercontent.com/46850780/127561018-0bd2f160-51d0-4239-92c0-d9f0f383b8af.png)

Click on "sAccessToken" in the list that appears, and try copying the value of that.
If it's still 603 chars, then we'll attempt fixing it - thank you!

**Comment by vtheskeleton** [comment]
Hello! I think what has happened is you have failed to copy the whole token

**Comment by vtheskeleton** [comment]
okay since you arent responding and nobody else has had this i will assume that this is not a saladbind bug and instead user error.
I will close this issue, but if you feel this is wrong just reopen it

**Comment by TheBlueBurger** [comment]
You could try to use manual, or use the new log option when it gets released
