### ISSUE TITLE
T-rex GPU monitoring fails to start

### ISSUE THREAD

**Issue by thepwrtank18** [VukkyLtd/SaladBind#5]
![image](https://user-images.githubusercontent.com/57580668/127537263-4322878a-2262-4671-98f5-c76bce697d5c.png)

**Comment by vtheskeleton** [comment]
Hello, I have failed to reproduce this issue.
I suggest asking Plerion, since they managed to fix it.
I will close this issue for now

**Comment by vtheskeleton** [comment]
Update drivers -Plerion

**Comment by vtheskeleton** [comment]
![image](https://user-images.githubusercontent.com/47392011/127622255-27bbf9e4-5d68-4c58-83fa-e7bbb720b64b.png)

**Comment by thepwrtank18** [comment]
My drivers are up to date, and this doesn't happen with Cli+.

**Comment by JovannMC** [comment]
He meant to downgrade the drivers, not update. Try downgrading your drivers to an older version.

**Comment by Vukkyy** [comment]
Unless it's proven that this is a BIND issue, I've tagged this as wontfix for now.
