### ISSUE TITLE
App crashes when launched from search results | Windows 11 22454.1000

### ISSUE THREAD

**Issue by Lyceris-chan** [VukkyLtd/SaladBind#80]
## Description
App crashes when launched from search results (start)

## How to reproduce
Windows 11 build 22454.1000

search for saladbind
run the app
output 

An unexpected error occured! Technical details:
EPERM: operation not permitted, mkdir './data'
This could be your antivirus.
? What do you want to do? (Use arrow keys)
> Write to log and exit
  Exit
![image](https://user-images.githubusercontent.com/52329982/133482837-9b31ceaf-d6be-49f7-a5c8-6cd6381e1a5a.png)

**Comment by Vukkyy** [comment]
This is a known bug, and happens because of how Windows Search opens the program. For now, you can make a shortcut on your desktop.

**Comment by TheBlueBurger** [comment]
I believe Windows 11 launches programs in another folder then its located in, you could make a shortcut here: `C:\Users\<username>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\SaladBind` and set the "Start in" to the correct folder
![image](https://user-images.githubusercontent.com/58081413/133483302-9311961a-8876-4759-a9a8-d7d4203a42b5.png)

**Comment by vtheskeleton** [comment]
If we were to get the absolute path for the creation of the data folder everything would be fine
right?

**Comment by Tpelaaja** [comment]
Probably not. Might break other systems.

**Comment by vtheskeleton** [comment]
> Probably not. Might break other systems.

How would using an absolute path break anything?

Alternatively we could start doing what salad does and put data folder in appdata/whatever on other os

**Comment by TheBlueBurger** [comment]
> > Probably not. Might break other systems.
> 
> How would using an absolute path break anything?
> 
> Alternatively we could start doing what salad does and put data folder in appdata/whatever on other os

Please don't do that aaaaaaaa

**Comment by Lyceris-chan** [comment]
Appears to be fixed using the 1.5.0 release in the announcement channel in the saladbind discord 

Windows 11: build 22463

**Comment by TheBlueBurger** [comment]
i dont think anything in 1.5.0 has affected this?

**Comment by Lyceris-chan** [comment]
just checked 1.4.2 still has the same issue its fixed on 1.5.0 doesn't appear miner related as it gives me the error message on application start

**Comment by Vukkyy** [comment]
Issue resolved for real.
